import type { DocumentMetadata } from "@/types/metadata"

export const defaultMetadata: DocumentMetadata = {
  fileName: "",
  fileType: "",
  fileSize: 0,
  documentProperties: {
    title: "",
    subject: "",
    creator: "",
    keywords: "",
    description: "",
    lastModifiedBy: "",
    revision: "1",
    created: "",
    modified: "",
    category: "",
    contentStatus: "",
    version: "",
    language: "zh-CN",
    identifier: "",
    source: "",
  },
  coreProperties: {
    dcTitle: "",
    dcSubject: "",
    dcCreator: "",
    dcDescription: "",
    dcKeywords: "",
    dcLanguage: "zh-CN",
    dcIdentifier: "",
    dcSource: "",
  },
  appProperties: {
    application: "Microsoft Office Word",
    appVersion: "16.0",
    company: "",
    manager: "",
    template: "Normal.dotm",
    totalTime: "0",
    pages: 0,
    words: 0,
    characters: 0,
    charactersWithSpaces: 0,
    paragraphs: 0,
    lines: 0,
  },
  annotationAuthors: [],
  revisionAuthors: [],
  xmpCreators: [],
  hasHiddenMarkers: false,
}
